config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  resources :posts, only: [:index, :show]
  resources :pages, only: [:index, :show]
  resources :comments, only: [:create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :username, presence: true
  validates :message, presence: true
  belongs_to :commentable, polymorphic: true
end

app/models/page.rb
class Page < ApplicationRecord
  has_many :comments, as: :commentable
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :comments, as: :commentable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to [@comment.commentable], notice: 'Comment created'
    else
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:username, :message, :commentable_id, :commentable_type)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @pages = Page.page(params[:page])
  end

  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.page(params[:page])
  end

  def show
    @post = Post.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comments/_form.html.haml
= simple_form_for [comment], html: {class: '' } do |f|
  = f.input :commentable_id, as: :hidden
  = f.input :commentable_type, as: :hidden
  = f.input :username
  = f.input :message
  = f.submit 'comentar', class: 'btn'

app/views/comments/_widget.html.haml
%hr

%h2 Comments
- commentable.comments.each do |comment|
  %div{id: "comment-#{comment.to_param}"}
    .row
      .col-sm-2
        %strong= comment.username
      .col-sm-8
        = link_to "#comment-#{comment.to_param}" do
          %span.glyphicon.glyphicon-link
          = time_ago_in_words(comment.created_at)
          ago
        %p= comment.message

= render 'comments/form', comment: commentable.comments.build

app/views/comments/new.html.haml
%h1= @comment.commentable.to_s

= render 'comments/form', comment: @comment

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}
    %title Commentable Demo
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all'
  %body
    %nav.navbar.navbar-inverse
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-controls" => "navbar", "aria-expanded" => "false", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.navbar-brand{href: root_path} Commentable Demo
        #navbar.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'pages', pages_path
            %li
              = link_to 'posts', posts_path
    .container
      = yield
    = javascript_include_tag 'application'

app/views/pages/index.html.haml
%h1 Pages

%ul
  - @pages.each do |page|
    %li= link_to page.title, page_path(page)

app/views/pages/show.html.haml
%h1= @page.title

%p= @page.content

= render 'comments/widget', commentable: @page

app/views/posts/index.html.haml
%h1 Posts

%ul
  - @posts.each do |post|
    %li= link_to post.title, page_path(post)

app/views/posts/show.html.haml
%h1= @post.title

%p= @post.content

= render 'comments/widget', commentable: @page

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml